Added /user api in auth
EdudishaSoftwares/pramaan pull request #7
Opened 2024-10-27 15:09 UTC by tusharthakurepc1

2024-10-27 17:46 UTC, pratik-edu commented on src/routes/external.route.ts
> +    this.router.post(`${prefix}/user`, this.sessionMiddleware.validate, asyncWrapper(this.authenticateController.initialUser));
Add Comments Here Please.
It should be only `/user` not `/auth/user `

2024-10-27 17:46 UTC, pratik-edu commented on src/controllers/authenticate.controller.ts
> +    const schoolDetails = await this.pathshalaInternal.getSchoolDetailByDomainName({ domain });
http call on controller layer 🤔??

2024-10-27 17:46 UTC, pratik-edu commented on src/controllers/authenticate.controller.ts
> +import { HandledError } from '@/exceptions/HandledError';
exception handling should be service layer

2024-10-28 10:39 UTC, HiAkshat requested changes

2024-10-28 10:39 UTC, HiAkshat commented on src/https/pathshala.http.ts
> +   * @param {payload} identifier for fetching school details
```suggestion
   * @param { Object } payload - identifier for fetching school details
```

2024-10-28 10:39 UTC, HiAkshat commented on src/https/pathshala.http.ts
> +  private pathshalaService = services.pathshala_service;
```suggestion
  // Services
  private pathshalaService = services.pathshala_service;
```

2024-10-28 10:39 UTC, HiAkshat commented on src/services/authenticate.service.ts
> +   * @param payload containing the identifier for fetching the school details
```suggestion
   * @param  {Object} identifier - containing the identifier for fetching the school details
```

2024-10-28 10:39 UTC, HiAkshat commented on src/typings/pathshala.d.ts
> +
remove space

2024-10-28 10:39 UTC, HiAkshat commented on src/typings/pathshala.d.ts
> +  boardAffiliation: 'CBSE' | 'ICSE' | 'State' | 'International';
make an enum and import

2024-10-28 10:40 UTC, HiAkshat commented
Run prettify to fix lint issue.

2024-10-28 10:48 UTC, pratik-edu commented on src/controllers/authenticate.controller.ts
> +    const schoolDetails = await this.authenticateService.initialUserRequest({ domain });
is there a need to send it in object.
as ideally one controller should call one service only.
no other controller can call same service directly.
so ATM its fine to send it without object.

2024-10-28 10:49 UTC, pratik-edu commented on src/services/authenticate.service.ts
> +import R, { identical } from 'ramda';
why identical??

2024-10-28 10:49 UTC, pratik-edu commented on src/services/authenticate.service.ts
> +      throw new HandledError('Domain not found');
Add status code here

2024-10-28 10:54 UTC, pratik-edu commented
> Run prettify to fix lint issue.

Valid Comment

2024-10-28 10:58 UTC, pratik-edu commented on src/routes/external.route.ts
>      this.initializeSchoolRoutes(`${this.path}/school`);
remove or mark all school related api as deprecated.
also update script to call internally to pathshala service for creation of school.

2024-11-01 15:06 UTC, pratik-edu approved these changes

2024-12-04 10:29 UTC, pratik-edu approved these changes

2024-12-04 10:37 UTC, AbhishekRathore1210 approved these changes

2024-12-04 10:40 UTC, HiAkshat approved these changes

2024-12-04 10:40 UTC, merged